management:
  metrics:
    export:
      datadog:
        api-key: ${DATADOG_API_KEY}
        application-key: ${DATADOG_APPLICATION_KEY}
        host-tag: ${spring.application.name}
        step: 10s
        enabled: true
