---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudpipelines/pipeline-base
    tag: latest

inputs:
  - name: code-repo
  - name: ci-scripts

run:
  path: ci-scripts/ci/tasks/unit-test.sh
